#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-xptr
Version  : 1.1.2
Release  : 2
URL      : https://cran.r-project.org/src/contrib/xptr_1.1.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/xptr_1.1.2.tar.gz
Summary  : Manipulating External Pointer
Group    : Development/Tools
License  : MIT
Requires: R-xptr-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
# Manipulating External Pointer
There is limited native support for external pointers in the R interface.
This package provides some basic tools to verify, create and modify 'externalptr' objects.

%package lib
Summary: lib components for the R-xptr package.
Group: Libraries

%description lib
lib components for the R-xptr package.


%prep
%setup -q -c -n xptr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582070814

%install
export SOURCE_DATE_EPOCH=1582070814
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xptr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xptr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xptr
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc xptr || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/xptr/DESCRIPTION
/usr/lib64/R/library/xptr/INDEX
/usr/lib64/R/library/xptr/LICENSE
/usr/lib64/R/library/xptr/Meta/Rd.rds
/usr/lib64/R/library/xptr/Meta/features.rds
/usr/lib64/R/library/xptr/Meta/hsearch.rds
/usr/lib64/R/library/xptr/Meta/links.rds
/usr/lib64/R/library/xptr/Meta/nsInfo.rds
/usr/lib64/R/library/xptr/Meta/package.rds
/usr/lib64/R/library/xptr/NAMESPACE
/usr/lib64/R/library/xptr/R/xptr
/usr/lib64/R/library/xptr/R/xptr.rdb
/usr/lib64/R/library/xptr/R/xptr.rdx
/usr/lib64/R/library/xptr/help/AnIndex
/usr/lib64/R/library/xptr/help/aliases.rds
/usr/lib64/R/library/xptr/help/paths.rds
/usr/lib64/R/library/xptr/help/xptr.rdb
/usr/lib64/R/library/xptr/help/xptr.rdx
/usr/lib64/R/library/xptr/html/00Index.html
/usr/lib64/R/library/xptr/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/xptr/libs/xptr.so
